In [1]:
import numpy as np

In [204]:
data = []
with open('input8.txt', 'r') as inf:
    for line in inf:
        data.append([int(i) for i in line.strip()])
forest = np.asarray(data)
visible = np.zeros(forest.shape, dtype=int)
visible[0] = 1
visible[:,0] = 1
visible[:,-1] = 1
visible[-1] =1
scenic = np.ones(forest.shape, dtype=int)

In [148]:
def mark_visible(trees, visible):
    i = 0
    for t,v in np.nditer([trees, visible]):
        if v == 0:
            if np.all(np.less(trees[0:i], trees[i])) or np.all(np.less(trees[i+1:], trees[i])):
                visible[i] = 1
        i+=1


In [76]:
nx, ny = forest.shape
for x in range(0, nx):
    mark_visible(forest[x], visible[x])

for y in range(0, ny):
    mark_visible(forest[:,y], visible[:,y])
    
print(np.sum(visible))

1803


In [205]:
def scenic_value(trees, scenic):
    imax = len(trees)
    # print(trees)
    for i in range(0, len(trees)):
        # print('i', i)
        w1 = np.argwhere(trees[0:i] >= trees[i])
        if len(w1) > 0:
            scenic[i] *= (i - np.max(w1))
            # print(1, w1, (i - np.max(w1)))
        else: 
            scenic[i] *= i
            # print(2, w1, i)
        w2 = np.argwhere(trees[i+1:] >= trees[i])
        if len(w2) > 0:
            scenic[i] *= (np.min(w2)+1)
            # print(3, w2, (np.min(w2)+1))
        else: 
            scenic[i] *= imax-(i+1)
            # print(4, w2, imax-(i+1))

In [206]:
nx, ny = forest.shape
for x in range(0, nx):
    scenic_value(forest[x], scenic[x])

for y in range(0, ny):
    scenic_value(forest[:,y], scenic[:,y])
    
print(scenic)
print(np.max(scenic))

[[ 0  0  0 ...  0  0  0]
 [ 0  1  1 ...  7  1  0]
 [ 0  4  8 ...  4  2  0]
 ...
 [ 0  1 12 ...  1  2  0]
 [ 0 25  1 ...  4  1  0]
 [ 0  0  0 ...  0  0  0]]
268912


In [192]:
scenic_value(forest[3], scenic[3])

[3 3 5 4 9]
i 0
2 [] 0
3 [[0]
 [1]
 [2]
 [3]] 1
i 1
1 [[0]] 1
3 [[0]
 [1]
 [2]] 1
i 2
2 [] 2
3 [[1]] 2
i 3
1 [[2]] 1
3 [[0]] 1
i 4
2 [] 4
4 [] 0


In [193]:
scenic

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 1, 4, 1, 0],
       [1, 1, 1, 1, 1]])

In [194]:
forest

array([[3, 0, 3, 7, 3],
       [2, 5, 5, 1, 2],
       [6, 5, 3, 3, 2],
       [3, 3, 5, 4, 9],
       [3, 5, 3, 9, 0]])

In [188]:
forest[3]

array([3, 3, 5, 4, 9])